-- 춘 대학교 워크북 과제
-- 3,10번 풀지 않음
--1번.
SELECT DEPARTMENT_NAME AS "학과 명", CATEGORY AS "계열"
FROM TB_DEPARTMENT;

--2번.
SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || '명 입니다.' AS "학과별 정원"
FROM TB_DEPARTMENT;

--4번.
SELECT STUDENT_NAME FROM TB_STUDENT 
WHERE STUDENT_NO IN('A513079','A513090','A513110','A513119');

--5번.
SELECT DEPARTMENT_NAME, CATEGORY FROM TB_DEPARTMENT
WHERE capacity BETWEEN 20 AND 30;

--6.
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE department_no IS NULL;

--7번
SELECT *
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

--8번
SELECT CLASS_NO FROM TB_CLASS
WHERE NOT preattending_class_no IS NULL;

--9번
SELECT DISTINCT CATEGORY FROM TB_DEPARTMENT;










