--NUMBER
--22BYTE 크기의 타입, 38자리를 표현할 수 있다.
--부동소수점 표현 방식과, 고정소수점 표현 방식이 있음
--부동소수점 표현 방식
--number_test NUMBER
INSERT INTO TB_TYPE(NUMBER_TEST) VALUES(12345.678);
SELECT NUMBER_TEST FROM TB_TYPE;

--고정소수점 표현 방식
-- NUMBER(PRECISION, SCALE)
-- PRECISION : 소수점을 포함한 전체 자리수
-- SCALE : 소수점 이하 자리수
-- SCALE을 생략할 경우 소수점 이하를 반올림하여 정수형만 저장
-- NUMBER_TEST1 NUMBER(7)
INSERT INTO TB_TYPE(NUMBER_TEST1) VALUES(12345.678);
SELECT NUMBER_TEST1 FROM TB_TYPE;

-- NUMBER_TEST2 NUMBER(7,1)
INSERT INTO TB_TYPE(NUMBER_TEST2) VALUES(12345.678);
SELECT * FROM TB_TYPE;

--NUMBER_TEST3 NUMBER(7,3)
--PRECISION - SCALE =  4, 즉 정수의 자리수는 4개까지 넣을 수 있다.
--INSERT INTO TB_TYPE(NUMBER_TEST3) VALUES(12345.678); ERROR 발생!
INSERT INTO TB_TYPE(NUMBER_TEST3) VALUES(1234.678);
SELECT NUMBER_TEST3 FROM TB_TYPE;

--NUMBER_TEST4 NUMBER(5,-2)
--10의 자리에서 반올림하여 입력
INSERT INTO TB_TYPE(NUMBER_TEST4) VALUES(12345.6789);
SELECT NUMBER_TEST4 FROM TB_TYPE;

-------------------------------------------------------------------------------
--SCALE이 PRECISION보다 큰 경우는 PRECISION이 소수점 오른쪽에 있는 유효자리수를 표시
--SCALE 정밀도 개념을 가지게 된다. SCALE의 숫자보다 소수점 자리수가 많은 것은 상관 없지만
-- 적으면은 에러가 발생한다.
--PRECISION은 유효자리수로 PRECISION 보다 유효자리가 적은 것은 상관없지만
-- 많으면 에러가 발생한다.

--NUMBER_TEST5 NUMBER(4,5)
--SCALE이 5자리까지 표현되어야 하지만 4자리까지만 지정되어있어서 에러가 발생
--INSERT INTO TB_TYPE(NUMBER_TEST5) VALUES(0.1234); ERROR발생
INSERT INTO TB_TYPE(NUMBER_TEST5) VALUES(0.00234);
SELECT NUMBER_TEST5 FROM TB_TYPE;

--NUMBER_TEST6 NUMBER(4,5)
INSERT INTO TB_TYPE(NUMBER_TEST5) VALUES(0.01234);
SELECT NUMBER_TEST5 FROM TB_TYPE;

--NUMBER_TEST7 NUMBER(3,7)
INSERT INTO TB_TYPE(NUMBER_TEST7) VALUES (0.0001234);

--NUMBER_TEST8 NUMBER(3,7)
INSERT INTO TB_TYPE(NUMBER_TEST8) VALUES (0.0000234);

COMMIT;





















